config/routes.rb
Rails.application.routes.draw do
  
  resources :ajuste_ubicacion do 
    collection do
      get "carga_clientes"
    end
  end

  resources :observaciones
  resources :reporte_visitas do
    collection do
      get "exportar_csv"
      get "mostrar_busqueda"
    end
  end

  resources :operaciones do
    collection do 
      get 'ver_fotografia'
      get 'ver_ubicacion'
      get 'ver_ubicacion_cliente'
      get 'actualizar_ubicacion'
      get 'remplazar_ubicacion'
    end
  end

  resources :exportar_ordenes_lectura do
    collection do
      get 'exportar_csv'
    end
  end


  devise_for :usuarios
  resources :menus do
    collection do
      get 'catastros'
    end
  end
  # > Ruta Principal
  root 'bienvenida#index'

  # > General
  resources :bienvenida do
    collection do
      get 'dashboard'
      get 'completitud'
      get 'productividad'
      get 'efectividad'
      get 'clientes_dudosos'
      get 'verificacion'
      get 'totales'
      get 'descargar_manual_web'
      get 'descargar_manual_app'
    end
  end

  # > Rutas Catastros
  # > Perfiles de Usuarios
  resources :perfils do
    collection do
      get 'exportar_csv'
      get 'exportar_pdf'
    end
  end
  match 'catastro/perfiles' => 'perfils#index', via: [:get, :post]

  # > Usuarios Administrativos
  resources :usuarios_administrativos do
    collection do
    	post 'cambiar'
      get 'modificar_contrasena'
      get 'exportar_pdf'
      get 'exportar_csv'
    end
  end
  match 'catastro/empleados/administrativos' => 'usuarios_administrativos#index', via: [:post, :get]

  # > Usuarios Agente de Terreno
  resources :usuarios_agentes_terreno do
    collection do
    	post 'cambiar'
      get 'modificar_contrasena'
      get 'exportar_pdf'
      get 'exportar_csv'
    end
  end
  match 'catastro/empleados/agentes_terreno' => 'usuarios_agentes_terreno#index', via: [:post, :get]

	# > Factor de Cobros
  resources :factor_cobros do
    collection do
      get 'carga_tramos'
    end
  end
  match 'catastro/tarifas' => 'factor_cobros#index', via: [:get, :post]

  # > Comunas Factor Cobros
  resources :comunas_factor_cobros do
    collection do
      get 'carga_comunas'
      get 'carga_provincias'
    end
  end
  match 'catastro/vinculacion_tarifa' => 'comunas_factor_cobros#index', via: [:post, :get]

  # > Claves y Observaciones de lectura
  resources :clave_lecturas do
    collection do
      post 'form_import'
      post 'import'
      get 'exportar_csv'
      get 'exportar_pdf'
    end
  end
  match 'catastro/clave_lecturas' => 'clave_lecturas#index', via: [:get, :post]
  match 'catastro/clave_lecturas_form_import' => 'clave_lecturas#form_import', via: [:get, :post]

  # > Observaciones de Reparto
  resources :observacion_repartos do
    collection do
      get 'exportar_csv'
      get 'exportar_pdf'
    end
  end
  match 'catastro/observacion_repartos' => 'observacion_repartos#index', via: [:get, :post]


  # > Routes Lectura
  # > Importar Ordenes de Lectura
  resources :importar_ordenes_lecturas do
    collection do
      # get :importar_csv, :as => :importar_csv
      post :importar_xml, :as => :importar_xml
      get 'carga_zonas'
      get 'carga_porciones'
    end
  end
  match 'lectura/operaciones/importar_ordenes_lectura' => 'importar_ordenes_lecturas#index', via: [:post, :get]
  match  'importar_ordenes_lecturas/import_csv'        =>          'importar_ordenes_lecturas#import_csv', via: [:post]
  match  'importar_ordenes_lecturas/import_xml'        =>          'importar_ordenes_lecturas#importar_xml', via: [:post]

  # Asignacion de Ordenes de Lectura
  resources :asignacions do
    collection do
      get 'carga_porciones'
      get 'carga_filtro'
      get 'carga_dividir_ruta_asignacion'
      get 'carga_dividir_ruta_desasignacion'
      get 'asignacion_lecturas'
      get 'asignacion_completa'
      get 'desasignacion_completa'
      get 'desasignacion_parcial'
      get 'asignacion_parcial'
      get 'carga_comunas'
    end
  end
  match 'lectura/operaciones/asignacion_lecturas' => 'asignacions#index', via: [:post, :get]

  # Impresión de Ruteros
  resources :impresion_ruteros do
    collection do
      get 'carga_filtro'
      get 'carga_porciones'
      get 'carga_rutas'
      get 'exportar_csv'
      get 'exportar_pdf'
    end
  end
  match 'lectura/operaciones/impresion_ruteros' => 'impresion_ruteros#index', via: [:post, :get]

  # Monitor de Lectores en Terreno
  resources :monitor_lectores do
    collection do
      get 'carga_filtro'
      get 'carga_ubicacion'
      get 'carga_zonas'
      get 'carga_porciones'
      get 'carga_rutas'
      get 'carga_comunas'
      get 'carga_lectores'
    end
  end
  match 'lectura/operaciones/monitor_lectores' => 'monitor_lectores#index', via: [:post, :get]

  # Cerrar Procesos de lectura
  resources :cerrar_procesos_lecturas do
    collection do
      get 'carga_filtro'
      get 'carga_zonas'
    end
  end
  match 'lectura/operaciones/cerrar_procesos_lecturas' => 'cerrar_procesos_lecturas#index', via: [:post, :get]

  # Lecturas Dictadas por Cliente
  resources :lectura_dictada_cliente do
    collection do
      get 'tabla_contenido'
      get 'form_lectura_dictada'
      get 'agregar_lectura_dictada'
      get 'alertas'
    end
  end
  match 'lectura/analisis_online/lectura_dictada_cliente' => 'lectura_dictada_cliente#index', via: [:post, :get]

  # Historico de lecturas de un cliente
  resources :historico_lecturas do
    collection do
      get 'carga_filtro'
      get 'carga_fotografia'
      get 'exportar_csv'
      get 'exportar_pdf'
      get 'carga_ubicacion'
    end
  end
  match 'lectura/analisis_online/historico_lecturas' => 'historico_lecturas#index', via: [:get, :post]

  resources :visualizacion_lecturas do
   collection do
    get 'cargar_ordenes'
    get 'cargar_porciones'
    get 'ver_ubicacion_cliente'
    get 'exportar_csv'
   end
  end
  match 'lectura/analisis_online/visualizacion_lecturas' => 'visualizacion_lecturas#index', via: [:get, :post]


  resources :clientes_improcedentes do
    collection do
     get 'cargar_ordenes'
     get 'cargar_porciones'
     get 'ver_ubicacion_cliente'
     get 'exportar_csv'
    end
   end
   match 'lectura/analisis_online/clientes_improcedentes' => 'clientes_improcedentes#index', via: [:get, :post]

  # Clientes Pendientes de Verificación
  resources :clientes_repaso do
    collection do
      get 'exportar_csv'
      get 'exportar_pdf'
      get 'carga_filtro'
    end
  end
  match 'lectura/analisis_online/clientes_pendientes_verificacion' => 'clientes_repaso#index', via: [:post, :get]

  # Reporte Efectividad Procesos
  resources :completitud_lecturas
  match 'lectura/reportes/efectividad_procesos' => 'completitud_lecturas#index', via: [:post, :get]

  # Reporte Efectividad Porción
  resources :reporte_efectividad_porcion do
    collection do
      get 'carga_porciones'
      get 'carga_filtro'
      get 'exportar_csv'
      get 'exportar_pdf'
    end
  end
  match 'lectura/reportes/efectividad_porcion' => 'reporte_efectividad_porcion#index', via: [:post, :get]

  #Reporte Efectividad por porcion
	resources :reporte_efectividad_lector do
    collection do
      get 'carga_lectores'
      get 'carga_filtro'
      get 'exportar_csv'
      get 'exportar_pdf'
    end
  end
  match 'lectura/reportes/efectividad_lector' => 'reporte_efectividad_lector#index', via: [:post, :get]

  #Reporte casa cerrada
	resources :reporte_casa_cerrada do
		collection do
			get 'carga_porciones'
      get 'carga_filtro'
      get 'exportar_excel'
			get 'exportar_pdf'
			get 'carga_lectores'
		end
  end
  match 'lectura/reportes/casa_cerrada' => 'reporte_casa_cerrada#index', via: [:post, :get]

  resources :reporte_control_coordenadas do # => OK
    collection do
      get 'carga_rutas'
      get 'carga_porciones'
      get 'carga_empleados'
      get 'carga_filtro'
      get 'carga_ubicacion'
      get 'exportar_csv'
      get 'exportar_pdf'
    end
  end
	match 'lectura/reportes/control_coordenadas_gps' => 'reporte_control_coordenadas#index', via: [:post, :get]

  #Reporte numero de intentos por lector
  resources :reporte_numero_intentos_lector do
    collection do
      get 'carga_porciones'
      get 'carga_empleados'
      get 'carga_comunas'
      get 'carga_filtro'
      get 'exportar_excel'
      get 'exportar_pdf'
    end
  end
  match 'lectura/reportes/numero_intentos_lector' => 'reporte_numero_intentos_lector#index', via: [:post, :get]

  # Reporte Tipo de Claves
	resources :reporte_tipos_claves do
    collection do
      get 'carga_porciones'
      get 'carga_filtro'
      get 'exportar_excel'
      get 'exportar_pdf'
    end
  end
  match 'lectura/reportes/tipos_claves' => 'reporte_tipos_claves#index', via: [:post, :get]

  resources :reporte_llenado_estanques do
    collection do
      get 'tabla_contenido'
      get 'porciones'
    end
  end
  match 'lectura/reportes/llenado_estanques' => 'reporte_llenado_estanques#index', via: [:post, :get]

  resources :reporte_control_horas_terreno do
    collection do
      get 'carga_porciones'
      get 'carga_empleados'
      get 'carga_comunas'
      get 'carga_filtro'
      get 'exportar_csv'
      get 'exportar_pdf'
    end
  end
  match 'lectura/reportes/control_horas_lector_terreno' => 'reporte_control_horas_terreno#index', via: [:post, :get]


	resources :reporte_nveces_sinlecturaefectiva do
    collection do
      get 'carga_porciones'
      get 'carga_filtro'
      get 'carga_comunas'
      get 'exportar_csv'
      get 'exportar_pdf'
    end
	end
  match 'reportes/efectividad_lector_proceso' => 'reporte_once#index', via: [:post, :get]


  # ---------------------------------------------------------------------- Reparto-------###############
 resources :carga_ordenes_reparto do #Importar Ordenes de Repartos
    collection do
      post :import
    end
  end
  match 'reparto/operaciones/importar_ordenes_reparto' => 'carga_ordenes_reparto#index', via: [:post, :get]

app/controllers/ajuste_ubicacion_controller.rb
class AjusteUbicacionController < ApplicationController
  respond_to :js
  require 'aws-sdk-s3'

  def index
    @clientes = Cliente.where(verificado: true).paginate(:page => params[:page], :per_page => 50)
    informacion()
    # exportarFotografias()
    #conexionS3()
  
  end
  
  def carga_clientes
    informacion()
    estado = params[:estado].to_i
    if estado == 1
      @clientes = Cliente.where(verificado: true)
    elsif estado == 2 
      @clientes = Cliente.where(verificado: false)
    else
      @clientes = Cliente.all
    end
    @clientes = @clientes.paginate(:page => params[:page], :per_page => 50)
    respond_with @clientes
  end

  def informacion
    clientes = Cliente.all
    @totalClientes = clientes.count
    @clientesVerificados = clientes.where(verificado: true).count
    @clientesSinVerificar = clientes.where(verificado: false).count
  end


  def conexionS3
    s3 = Aws::S3::Resource.new(region:'us-east-1')
    my_bucket = s3.bucket('aguasandinas')
    my_bucket.objects.limit(100).each do |obj|
      p obj
    end
  end

  bucketPrincipal = 'aguasandinas'
  bucketClientes = 'clientes_aguasandinas'

  def exportarFotografias
    bucketPrincipal = 'aguasandinas'
    bucketClientes = 'clientes_aguasandinas'
    s3 = Aws::S3::Resource.new(region:'us-east-1')
    #s3.create_bucket(bucket: bucketClientes)
    clientes = Cliente.all
    clientes.each do |cliente|
      new_path = cliente.numero_cliente
      ordenLectura = OrdenLectura.where(estado_lectura_id: 4, cliente_id: cliente.id)
      if !ordenLectura.blank?
        fotografias = ordenLectura.last.detalle_orden_lectura.first.fotografium
        fotografias.each do |fotografia|
          aws_path = fotografia.archivo.to_s
          p aws_path
          aws_object = AWS::S3::S3Object.find aws_path, 'aguasandinas'
          s3.copy_object(bucket: bucket,copy_source: "#{bucketPrincipal}/fotografias/#{fotografia.archivo}",key: 'file1')
          s3.copy_object(bucket: bucket,copy_source: "#{bucketClientes}/fotografias/#{new_path}",key: 'file2')
        end
        nombreCarpeta = cliente.numero_cliente
      end
    end
  end

end

app/helpers/ajuste_ubicacion_helper.rb
module AjusteUbicacionHelper
end

app/views/ajuste_ubicacion/_carga_clientes.html.erb
<div id="carga_clientes">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="alert alert-warning">
          <ul>
            <li>
              <% if !@totalClientes.nil? %>
                <label>Clientes Registrados: <%= @totalClientes%></label><br>
              <% end %>
            </li>
            <li>
              <% if !@clientesVerificados.nil? %>
                <label>Clientes Verificados: <%= @clientesVerificados %></label><br>
              <% end %>
            </li>
            <li>
              <% if !@clientesSinVerificar.nil? %>
                <label>Clientes Sin Verificar <%= @clientesSinVerificar %> </label>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <br>
    <div class="card">
      <div class="card-header"><span class="mdi mdi-account"></span> Clientes</div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-striped table-hover table-sm table-bordered animated fadeIn fast">
            <thead>
              <tr>
                <th colspan="3">Operaciones</th>
                <th>ID</th>
                <th>Número cliente</th>
                <th>Cliente</th>
                <th>Dirección</th>
                <th>Sub Empresa</th>
                <th>Verificado</th>
              </tr>
            </thead>
            <tbody>
              <% if !@clientes.nil? %>
                <% @clientes.each do |cliente| %>
                  <tr>
                    <td>
                      <button onclick="verFotografia('<%= cliente.orden_lectura.last.id%>');" class="btn btn-warning btn-sm" data-toggle="tooltip" data-placement="top" title="Fotografías">
                        <span class="mdi mdi-camera"></span>
                      </button
                    </td>
                    <td> 
                      <button onclick="verUbicacion('<%=cliente.orden_lectura.last.id%>')" type="button" class="btn btn-danger btn-sm" data-toggle="tooltip" data-placement="top" title="Ubicación Lector">
                        <span class="mdi mdi-map-marker"></span>
                      </button>
                    </td>
                    <td> 
                      <button onclick="verUbicacionCliente('<%=cliente.id%>')"type="button" class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="top" title="Ubicación Recinto">
                        <span class="mdi mdi-map-marker"></span>
                      </button>
                    </td>
                    <td><%=cliente.id%></td>
                    <td><%=cliente.numero_cliente%></td>
                    <td><%=cliente.nombre%></td>
                    <td><%=cliente.direccion%></td>
                    <td><%=cliente.orden_lectura.first.subempresa.razon_social%> </td>
                    <td>
                      <% if cliente.verificado %>
                        <input type="checkbox" checked>
                      <% else %>
                        <input type="checkbox" >
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
        <div id="will_paginate_id" class="row h-100 justify-content-center align-items-center">
          <% if !@clientes.nil?%>
            <%= will_paginate @clientes %> <br>
          <% end %>
        </div>
      </div>
    </div>
  </div>
    

        <!-- Modal Fotografia -->
<div id="modal1">
    <div id="modalFotografia" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">
      <!-- Modal content-->
      <div class="modal-content" >
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle"> <span class="mdi mdi-camera"></span> Fotografías </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= render 'operaciones/ver_fotografia' %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
        </div>
      </div>
    </div>
  </div>
  </div>

        <div id="modal2">
            <div id="modalUbicacion" class="modal fade" role="dialog">
              <div class="modal-dialog modal-lg">
                <!-- Modal content-->
                <div class="modal-content"  >
                  <div class="modal-body">
                    <div class="card">
                      <ol class="breadcrumb">
                        <li class="breadcrumb-item"><%= link_to '<i class="mdi mdi-home"></i>'.html_safe, { :action => "index", :controller => :bienvenida }%></span></li>
                        <li class="breadcrumb-item">Lectura </li>
                        <li class="breadcrumb-item">Operaciones </li>
                        <li class="breadcrumb-item"><%=link_to 'Historico Lecturas', lectura_operaciones_monitor_lectores_path%></li>
                        <li class="breadcrumb-item active">Ubicación Lectura</li>
                      </ol>
                    </div>
                    <br>
                    <%= render partial: 'operaciones/ver_ubicacion' %>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-danger" data-dismiss="modal" >Cerrar</button>
                      <button type="button" class="btn btn-success  pull-left" onclick="mapa();">Refrescar Mapa</button>
                    </div>
                </div>
              </div>
            </div>
          </div>
          </div>
          <iv id="modal3">
            <div id="modalUbicacionCliente" class="modal fade" role="dialog">
              <div class="modal-dialog modal-lg">
                <!-- Modal content-->
                <div class="modal-content"  >
                  <div class="modal-body">
                    <div class="card">
                      <ol class="breadcrumb">
                        <li class="breadcrumb-item"><%= link_to '<i class="mdi mdi-home"></i>'.html_safe, { :action => "index", :controller => :bienvenida }%></span></li>
                        <li class="breadcrumb-item">Lectura </li>
                        <li class="breadcrumb-item">Operaciones </li>
                        <li class="breadcrumb-item"><%=link_to 'Historico Lecturas', lectura_operaciones_monitor_lectores_path%></li>
                        <li class="breadcrumb-item active">Ubicación Lectura</li>
                      </ol>
                    </div>
                    <br>
                    <%= render partial: 'visualizacion_lecturas/ver_ubicacion_cliente' %>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-danger" data-dismiss="modal" >Cerrar</button>
                      <button type="button" class="btn btn-success  pull-left" onclick="mapa();">Refrescar Mapa</button>
                    </div>
                </div>
              </div>
            </div>
          </div>
          </div>
          
         

<script type="text/javascript">
 
  function verUbicacion(orden_id){
    $.ajax({
      url:"<%=url_for :controller => 'operaciones', :action => 'ver_ubicacion', :format => :js %>",
      data:'orden_id=' + encodeURIComponent(orden_id),
      cache:false,
      success:function (data) {}
    })
    $('#modalUbicacion').modal();
    mapa();
  }      
        
  function verUbicacionCliente(cliente){
    $.ajax({
      url:"<%=url_for :controller => 'operaciones', :action => 'ver_ubicacion_cliente', :format => :js %>",
      data:'cliente=' + encodeURIComponent(cliente),
      cache:false,
      success:function (data) {}
    })
    $('#modalUbicacionCliente').modal();
    //mapaRecinto();
  }
  // # > Mostrar Fotografias
  function verFotografia(orden_id){
    $.ajax({
      url:"<%=url_for :controller => 'operaciones',:action => 'ver_fotografia', :format => :js %>",
      data:'id_orden=' + encodeURIComponent(orden_id),
      cache:false,
      success:function (data) {}
    })
    $('#modalFotografia').modal();
	}
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>

</div>

app/views/ajuste_ubicacion/carga_clientes.js.erb
$("#carga_clientes").html("<%= escape_javascript(render partial: 'carga_clientes') %>"); 
$('.pagination a').attr('data-remote', 'true');

app/views/ajuste_ubicacion/index.html.erb
<title>Ajustes GPS</title>
<div class="container-fluid">
	<div class="card">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><%= link_to '<i class="mdi mdi-home"></i>'.html_safe, { :action => "index", :controller => :bienvenida }%></span></li>
			<li class="breadcrumb-item">Lecturas </li>
			<li class="breadcrumb-item">Análisis Online</li>
			<li class="breadcrumb-item active">Ajuste ubicación GPS</li>
		</ol>
  </div>
</div>
<br>
<div class="container-fluid">
  <div class="card">
    <div class="card-header"><span class="mdi mdi-magnify"></span> Buscador</div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-4">
          <span class="mdi mdi-animation"></span> <label>Estado:</label><br>
          <select name="select" onchange="cargaClientes();" id="estado" class="custom-select custom-select-sm">
            <option value="1">Verificado</option> 
            <option value="2">Sin Verificar</option>
          </select>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<div class="container-fluid">
  <%= render "carga_clientes" %>
</div>


<script>
  function cargaClientes() {
    /*Carga las porciones disponibles de una zona */
		var estado = document.getElementById("estado").value;
		$.ajax({
			url: "<%=url_for :controller => 'ajuste_ubicacion',:action => 'carga_clientes' %>",
			data: 'estado=' + encodeURIComponent(estado),
			cache: false,
			success: function(data) {}
		})
	}
</script>